---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Global
- type: heading
  label: Team Section
- type: directory
  path: content/Team Members
  label: Members Pages
  create: all
  match: "*"
  templates:
  - team-member
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
- type: heading
  label: Landing Page
- type: document
  path: content/Sections/jumbotron-section.md
  label: Jumbotron Section
- type: document
  path: content/Sections/product-section.md
  label: Product Section
- type: document
  path: content/Sections/team-section.md
  label: Team Section
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.42.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.42.1
