---
label: Product Info
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: icon
  type: file
  config:
    maxSize: 64
  label: Icon
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
